#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 masasao　　　　　
# SPDX-License-Identifier: BSD-3-Clause
import sys

try:
    data1 = float(sys.argv[1])
    
    if data1 == 3:
        try:
            data2 = float(sys.argv[2])
        except ValueError:
            print("整数か少数を入力してください")
            sys.exit()
        except IndexError:
            print("空欄があるため実行できません")
            sys.exit()
        try:
            data3 = float(sys.argv[3])
        except ValueError:
            print("整数か少数を入力してください")
            sys.exit()
        except IndexError:
            print("空欄があるため実行できません")
            sys.exit()

        data4 = (data2 * data3)/2
        print(data4)

    elif data1 == 4:
        try:
            data2 = float(sys.argv[2])
        except ValueError:
            print("整数か少数を入力してください")
            sys.exit()
        except IndexError:
            print("空欄があるため実行できません")
            sys.exit()
        try:
            data3 = float(sys.argv[3])
        except ValueError:
            print("整数か少数を入力してください")
            sys.exit()
        except IndexError:
            print("空欄があるため実行できません")
            sys.exit()
        data4 = (data2 * data3)
        print(data4)
    else:
        print("正しく実行できませんでした。説明をもう一度読んでください。")
except ValueError:
    print("整数、または少数を入力してください。")
except IndexError:
    print("何の計算を行うか指定されていません")
                            
    
